### ISSUE TITLE
umount before mount ?

### ISSUE THREAD

**Issue by dft601** [hvalev/mergerfs-docker#51]
Hi,

sorry, I am really new to linux and docker...

Got your container working.. Thanks for this :-)

I had 2 or 3 times the problem that the container was shut down for a moment while mounting disks on my qnap.
After that the container does not start again, because the mount already exists.

`Fehler	2023-08-21	08:46:10	admin	---	Container Station	Docker Engine - Community / 20.10.22-qnap7	Container Station	Containers	[Container Station] Failed to start container "mergerfs". Error message: Error response from daemon: error while creating mount source path '/share/Alle-Medien/Alle-Medien': mkdir /share/Alle-Medien/Alle-Medien: file exists`

Can I change the yaml in that way, that a possible mount is unmounted before ?

Mike

**Comment by hvalev** [comment]
The PR #74 I just merged should resolve this issue. Let me know if it persists.
