### ISSUE TITLE
Docker doesn't change MacOS folder

### ISSUE THREAD

**Issue by ahm99** [hvalev/mergerfs-docker#78]
I can see the merged folded in the container terminal with all of the disks contents, and I can see that merged folder is created in may macOS finder, but it's empty

> mergerfs:
> image: hvalev/mergerfs:latest
> container_name: mergerfs
> cap_add:
> - SYS_ADMIN
> devices:
> - /dev/fuse:/dev/fuse
> environment:
> - PUID=501
> - PGID=20
> volumes:
> - /Volumes/NVMe/Docker/mergerfs:/config
> - /Volumes/disk1/Data:/disks/disk1
> - /Volumes/disk2/Data:/disks/disk2
> - /Volumes/disk-3/Data:/disks/disk3
> - /Volumes/disk-4/Data:/disks/disk4
> - /Volumes/disk-1/Merged:/merged:shared
> restart: always
>

**Comment by hvalev** [comment]
I don't own a mac and I can't really test this. From some cursory look into it, it seems that mergerfs has some problems with macOS. It's best to try to do a native install of mergerfs to eliminate docker as a source of error and if the problem persists, reach out to the [origin project repository](https://github.com/trapexit/mergerfs/issues)
