### ISSUE TITLE
Merged directory is inaccessible after first shutdown

### ISSUE THREAD

**Issue by Cheezzhead** [hvalev/mergerfs-docker#79]
My mergerfs setup works the first time it runs. However, after shutting down or restarting the container, I get this error:

```
docker: Error response from daemon: error while creating mount source path '/media/home/test_merged': mkdir /media/home/test_merged: file exists.
```

From there, the problems get weirder. I can't read, access, or delete the directory even with the mergerfs container down:

```
[/media/home] $ ls -alh
ls: cannot access 'test_merged': Transport endpoint is not connected
d?????????  ? ?    ?       ?            ? test_merged/

[/media/home] $ sudo rm -rf test_merged 
rm: cannot remove 'test_merged': Is a directory
```

Attempting to start the container again, or inspect the mountpoint with `df /media/home/test_merged`, result in a 'Transport endpoint is not connected' error. Essentially the only way to continue is to use a new mount directory.

One of the drives to be merged is an rclone mount within another docker container. Perhaps this is causing the issue?

```
services:
  rclone:
    image: rclone/rclone:latest
    container_name: rclone
    privileged: true
    ports: [5574:5574/tcp]
    healthcheck:
      test: sh -c "[ -f /data/drive.anchor ]"
    command: 
      mount my_remote:/media /data
      --umask 002 --uid ${PUID} --gid ${PGID}
      --cache-dir /cache
      --log-file /log/mount.log
      -vvv
      --allow-other
      --allow-non-empty
      --dir-cache-time 10m
      --poll-interval 15s
      --vfs-cache-mode full
      --vfs-cache-max-size 100G
      --vfs-cache-max-age 240h
      --vfs-cache-poll-interval 5m
      --vfs-read-ahead 2G
      --vfs-write-back 1h
      --rc
      --rc-no-auth
      --rc-addr=:5574
    volumes:
      - ${HOME}/.config/rclone:/config/rclone
      - ${HOME}/.ssh/id_remote:${HOME}/.ssh/id_remote:ro
      - rclone_cache:/cache
      - /mnt/media:/data:shared
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - /etc/fuse.conf:/etc/fuse.conf:ro
      - /var/log/rclone:/log
  
  mergerfs:
    image: hvalev/mergerfs:latest
    container_name: mergerfs
    privileged: true
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse:/dev/fuse
    depends_on:
      rclone:
        condition: service_healthy
    volumes:
       - ${STORAGE_DIR}/local:/disks/local
       - /mnt/media:/disks/media:shared
       - ${STORAGE_DIR}/test_merged:/merged:shared
       - ./mergerfs/parameters.conf:/config/parameters.conf:ro
```

Parameters.conf (Unused parameters removed for clarity):
```
dropcacheonclose=true
category.create=ff
cache.files=partial
statfs_ignore=nc

# CUSTOM: helps with plex scans
func.getattr=newest
```

**Comment by Cheezzhead** [comment]
Upon further inspection it seems the problem is more related to rclone then mergerfs. Closing!

**Comment by hvalev** [comment]
No worries, it seems like a stale handle that was not being properly released upon closing the container. You could try to capture the SIGTERM or SIGKILL signal sent from the docker daemon to containers when shutting down rclone and force a umount on the path in question. That way the mounted volume and it will be properly released to the host.

**Comment by Cheezzhead** [comment]
Thanks for the tip, definitely worth checking out.

For anyone else with similar issues: the problem occurs when rclone shuts down before mergerfs has a chance to unmount. The stale handle can be cleaned up using `fusermount -z -u /path/to/mnt`.
Optimally the `depends_on` option should always stop mergerfs before rclone is stopped/restarted, and this is the case as long you issue commands to the whole compose stack. However when stopping/restarting *just* the rclone container it doesn't respect this order. My love/hate relationship with `depends_on` continues...
